name: dotnet

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore --configfile Nuget.config

    - name: Build
      run: dotnet build --nologo --no-restore --configuration Release

    - name: Publish
      run: dotnet publish --nologo --no-restore --no-build